Repository hazelcast/hazelcast-jdbc, pull requests merged in 2023-02, with the labels that each got.

#219 [HZ-2033] Release hazelcast-jdbc-enterprise JAR besides the hazelcast-jdbc
  .github/workflows/deploy-release.yml
  .github/workflows/deploy-snapshot.yml
  META-INF/MANIFEST.MF
  META-INF/maven/com.hazelcast/hazelcast-jdbc/pom.properties
  META-INF/maven/com.hazelcast/hazelcast-jdbc/pom.xml
  hazelcast-jdbc-core/LICENSE
  hazelcast-jdbc-core/pom.xml
  hazelcast-jdbc-core/src/main/java/com/hazelcast/jdbc/Constants.java
  hazelcast-jdbc-core/src/main/java/com/hazelcast/jdbc/Driver.java
  hazelcast-jdbc-core/src/main/java/com/hazelcast/jdbc/FixedRowsSqlResult.java
  hazelcast-jdbc-core/src/main/java/com/hazelcast/jdbc/HazelcastConfigFactory.java
  hazelcast-jdbc-core/src/main/java/com/hazelcast/jdbc/HazelcastSqlClient.java
  hazelcast-jdbc-core/src/main/java/com/hazelcast/jdbc/JdbcConnection.java
  hazelcast-jdbc-core/src/main/java/com/hazelcast/jdbc/JdbcDataBaseMetadata.java
  hazelcast-jdbc-core/src/main/java/com/hazelcast/jdbc/JdbcPreparedStatement.java
  hazelcast-jdbc-core/src/main/java/com/hazelcast/jdbc/JdbcResultSet.java
  hazelcast-jdbc-core/src/main/java/com/hazelcast/jdbc/JdbcResultSetMetaData.java
  hazelcast-jdbc-core/src/main/java/com/hazelcast/jdbc/JdbcStatement.java
  hazelcast-jdbc-core/src/main/java/com/hazelcast/jdbc/JdbcUrl.java
  hazelcast-jdbc-core/src/main/java/com/hazelcast/jdbc/JdbcUtils.java
  hazelcast-jdbc-core/src/main/java/com/hazelcast/jdbc/ParameterList.java
  hazelcast-jdbc-core/src/main/java/com/hazelcast/jdbc/TypeConverter.java
  hazelcast-jdbc-core/src/main/java/com/hazelcast/jdbc/TypeUtil.java
  hazelcast-jdbc-core/src/main/java/com/hazelcast/jdbc/package-info.java
  hazelcast-jdbc-core/src/main/resources/META-INF/services/java.sql.Driver
  hazelcast-jdbc-core/src/test/java/com/hazelcast/jdbc/DriverEnvironmentsTest.java
  hazelcast-jdbc-core/src/test/java/com/hazelcast/jdbc/DriverImdgTest.java
  hazelcast-jdbc-core/src/test/java/com/hazelcast/jdbc/DriverTest.java
  hazelcast-jdbc-core/src/test/java/com/hazelcast/jdbc/DriverTypeConversionTest.java
  hazelcast-jdbc-core/src/test/java/com/hazelcast/jdbc/HazelcastConfigFactoryTest.java
  hazelcast-jdbc-core/src/test/java/com/hazelcast/jdbc/JdbcConnectionIntegrationTest.java
  hazelcast-jdbc-core/src/test/java/com/hazelcast/jdbc/JdbcConnectionTest.java
  hazelcast-jdbc-core/src/test/java/com/hazelcast/jdbc/JdbcDataBaseMetadataTest.java
  hazelcast-jdbc-core/src/test/java/com/hazelcast/jdbc/JdbcPreparedStatementTest.java
  hazelcast-jdbc-core/src/test/java/com/hazelcast/jdbc/JdbcResultSetMetaDataTest.java
  hazelcast-jdbc-core/src/test/java/com/hazelcast/jdbc/JdbcResultSetTest.java
  hazelcast-jdbc-core/src/test/java/com/hazelcast/jdbc/JdbcStatementQueryTypeTest.java
  hazelcast-jdbc-core/src/test/java/com/hazelcast/jdbc/JdbcStatementTest.java
  hazelcast-jdbc-core/src/test/java/com/hazelcast/jdbc/JdbcTestSupport.java
  hazelcast-jdbc-core/src/test/java/com/hazelcast/jdbc/JdbcUrlTest.java
  hazelcast-jdbc-core/src/test/java/com/hazelcast/jdbc/ParameterListTest.java
  hazelcast-jdbc-core/src/test/java/com/hazelcast/jdbc/Person.java
  hazelcast-jdbc-core/src/test/java/com/hazelcast/jdbc/TypesHolder.java
  hazelcast-jdbc-core/src/test/java/com/hazelcast/jdbc/ValuesWrapper.java
  hazelcast-jdbc-enterprise/pom.xml
  hazelcast-jdbc/LICENSE
  hazelcast-jdbc/pom.xml
  pom.xml
  src/main/resources/META-INF/services/java.sql.Driver
Labels: safe-to-test

#222 Fix config for Viridian
  .github/workflows/build.yml
  .github/workflows/deploy-release.yml
  .github/workflows/deploy-snapshot.yml
  README.md
  checkstyle/ClassHeader.txt
  checkstyle/checkstyle.xml
  checkstyle/suppressions.xml
  hazelcast-jdbc-core/pom.xml
  hazelcast-jdbc-core/src/main/java/com/hazelcast/jdbc/Constants.java
  hazelcast-jdbc-core/src/main/java/com/hazelcast/jdbc/Driver.java
  hazelcast-jdbc-core/src/main/java/com/hazelcast/jdbc/FixedRowsSqlResult.java
  hazelcast-jdbc-core/src/main/java/com/hazelcast/jdbc/HazelcastConfigFactory.java
  hazelcast-jdbc-core/src/main/java/com/hazelcast/jdbc/HazelcastSqlClient.java
  hazelcast-jdbc-core/src/main/java/com/hazelcast/jdbc/JdbcConnection.java
  hazelcast-jdbc-core/src/main/java/com/hazelcast/jdbc/JdbcDataBaseMetadata.java
  hazelcast-jdbc-core/src/main/java/com/hazelcast/jdbc/JdbcPreparedStatement.java
  hazelcast-jdbc-core/src/main/java/com/hazelcast/jdbc/JdbcResultSet.java
  hazelcast-jdbc-core/src/main/java/com/hazelcast/jdbc/JdbcResultSetMetaData.java
  hazelcast-jdbc-core/src/main/java/com/hazelcast/jdbc/JdbcStatement.java
  hazelcast-jdbc-core/src/main/java/com/hazelcast/jdbc/JdbcUrl.java
  hazelcast-jdbc-core/src/main/java/com/hazelcast/jdbc/JdbcUtils.java
  hazelcast-jdbc-core/src/main/java/com/hazelcast/jdbc/ParameterList.java
  hazelcast-jdbc-core/src/main/java/com/hazelcast/jdbc/TypeConverter.java
  hazelcast-jdbc-core/src/main/java/com/hazelcast/jdbc/TypeUtil.java
  hazelcast-jdbc-core/src/main/java/com/hazelcast/jdbc/package-info.java
  hazelcast-jdbc-core/src/main/resources/META-INF/services/java.sql.Driver
  hazelcast-jdbc-core/src/test/java/com/hazelcast/jdbc/DriverEnvironmentsTest.java
  hazelcast-jdbc-core/src/test/java/com/hazelcast/jdbc/DriverImdgTest.java
  hazelcast-jdbc-core/src/test/java/com/hazelcast/jdbc/DriverTest.java
  hazelcast-jdbc-core/src/test/java/com/hazelcast/jdbc/DriverTypeConversionTest.java
  hazelcast-jdbc-core/src/test/java/com/hazelcast/jdbc/HazelcastConfigFactoryTest.java
  hazelcast-jdbc-core/src/test/java/com/hazelcast/jdbc/JdbcConnectionIntegrationTest.java
  hazelcast-jdbc-core/src/test/java/com/hazelcast/jdbc/JdbcConnectionTest.java
  hazelcast-jdbc-core/src/test/java/com/hazelcast/jdbc/JdbcDataBaseMetadataTest.java
  hazelcast-jdbc-core/src/test/java/com/hazelcast/jdbc/JdbcPreparedStatementTest.java
  hazelcast-jdbc-core/src/test/java/com/hazelcast/jdbc/JdbcResultSetMetaDataTest.java
  hazelcast-jdbc-core/src/test/java/com/hazelcast/jdbc/JdbcResultSetTest.java
  hazelcast-jdbc-core/src/test/java/com/hazelcast/jdbc/JdbcStatementQueryTypeTest.java
  hazelcast-jdbc-core/src/test/java/com/hazelcast/jdbc/JdbcStatementTest.java
  hazelcast-jdbc-core/src/test/java/com/hazelcast/jdbc/JdbcTestSupport.java
  hazelcast-jdbc-core/src/test/java/com/hazelcast/jdbc/JdbcUrlTest.java
  hazelcast-jdbc-core/src/test/java/com/hazelcast/jdbc/ParameterListTest.java
  hazelcast-jdbc-core/src/test/java/com/hazelcast/jdbc/Person.java
  hazelcast-jdbc-core/src/test/java/com/hazelcast/jdbc/TypesHolder.java
  hazelcast-jdbc-core/src/test/java/com/hazelcast/jdbc/ValuesWrapper.java
  hazelcast-jdbc-enterprise/pom.xml
  hazelcast-jdbc/pom.xml
  pom.xml
Labels: bug, safe-to-test

#223 Improve release automation
  .github/workflows/build.yml
  .github/workflows/deploy-release.yml
Labels: safe-to-test

#233 Upgrade Hazelcast to 5.2.2
  pom.xml
Labels: safe-to-test

#235 Upgrade Hazelcast dependency version to 5.2.2 (5.2.z)
  pom.xml
Labels: dependencies
